In [1]:
import pandas as pd
from pycaret.classification import *

# Load Data

In [2]:
df = pd.read_csv('adult.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,y
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

# Default Modeling

In [3]:
setup_default = ClassificationExperiment()
setup_default.setup(df, target='y', experiment_name='adult', log_experiment=True)

2023/03/19 17:57:17 INFO mlflow.tracking.fluent: Experiment with name 'adult' does not exist. Creating a new experiment.

In [4]:
best_model_default = setup_default.compare_models()

# Normalize Data

In [5]:
setup_norm = ClassificationExperiment()
setup_norm.setup(df, target='y', experiment_name='adult', log_experiment=True,
                 normalize=True, normalize_method='zscore')

In [6]:
best_model_norm = setup_norm.compare_models()

# Top 5 Predictor

In [7]:
setup_top5 = ClassificationExperiment()
setup_top5.setup(df, target='y', experiment_name='adult', log_experiment=True,
                 n_features_to_select=5)

2023/03/19 18:03:30 INFO mlflow.tracking.fluent: Experiment with name 'adult-dataset' does not exist. Creating a new experiment.

In [8]:
best_model_top5 = setup_top5.compare_models()

# Outlier Removal

In [9]:
setup_outr = ClassificationExperiment()
setup_outr.setup(df, target='y', experiment_name='adult', log_experiment=True,
                 remove_outliers=True)

In [10]:
best_model_outr = setup_outr.compare_models()

# Gabungan

In [11]:
setup_all = ClassificationExperiment()
setup_all.setup(df, target='y', experiment_name='adult', log_experiment=True,
                normalize=True, normalize_method='zscore',
                n_features_to_select=5, remove_outliers=True)

In [12]:
best_model_all = setup_all.compare_models()

Initiated  . . . . . . . . . . . . . . . . . .                18:12:12
Status     . . . . . . . . . . . . . . . . . .        Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  K Neighbors Classifier

Processing:   0%|          | 0/61 [00:00<?, ?it/s]